export const DAVAO_BARANGAYS = [
  "Acacia","Agdao","Alambre","Atan-Awe","Bago Gallera","Bago Oshiro","Baguio",
  "Balengaeng","Baliok","Bangkas Heights","Baracatan","Bato","Bayabas",
  "Biao Escuela","Biao Guianga","Biao Joaquin","Binugao","Bucana","Buhangin",
  "Bunawan","Cabantian","Cadalian","Calinan","Callawa","Camansi","Carmen",
  "Catalunan Grande","Catalunan Pequeño","Catigan","Cawayan","Colosas",
  "Communal","Crossing Bayabas","Dacudao","Dalag","Dalagdag","Daliao",
  "Daliaon Plantation","Dominga","Dumoy","Eden","Fatima","Gatungan","Gumalang",
  "Ilang","Indangan","Kilate","Lacson","Lamanan","Lampianao","Langub",
  "Alejandra Navarro","Lizada","Los Amigos","Lubogan","Lumiad","Ma-a","Mabuhay",
  "Magtuod","Mahayag","Malabog","Malagos","Malamba","Manambulan","Mandug",
  "Manuel Guianga","Mapula","Marapangi","Marilog","Matina Aplaya",
  "Matina Crossing","Matina Pangi","Matina Biao","Mintal","Mudiang","Mulig",
  "New Carmen","New Valencia","Pampanga","Panacan","Panalum","Pandaitan",
  "Pangyan","Paquibato","Paradise Embak","Riverside","Salapawan","Salaysay",
  "San Isidro","Sasa","Sibulan","Sirawan","Sirib","Suawan","Subasta","Sumimao",
  "Tacunan","Tagakpan","Tagluno","Tagurano","Talandang","Talomo","Talomo River",
  "Tamayong","Tambobong","Tamugan","Tapak","Tawan-tawan","Tibuloy","Tibungco",
  "Tigatto","Toril","Tugbok","Tungakalan","Ula","Wangan","Wines",
  "Barangay 1-A","Barangay 2-A","Barangay 3-A","Barangay 4-A","Barangay 5-A",
  "Barangay 6-A","Barangay 7-A","Barangay 8-A","Barangay 9-A","Barangay 10-A",
  "Barangay 11-B","Barangay 12-B","Barangay 13-B","Barangay 14-B","Barangay 15-B",
  "Barangay 16-B","Barangay 17-B","Barangay 18-B","Barangay 19-B","Barangay 20-B",
  "Barangay 21-C","Barangay 22-C","Barangay 23-C","Barangay 24-C","Barangay 25-C",
  "Barangay 26-C","Barangay 27-C","Barangay 28-C","Barangay 29-C","Barangay 30-C",
  "Barangay 31-D","Barangay 32-D","Barangay 33-D","Barangay 34-D","Barangay 35-D",
  "Barangay 36-D","Barangay 37-D","Barangay 38-D","Barangay 39-D","Barangay 40-D",
  "Angalan","Baganihan","Bago Aplaya","Bantol","Buda","Centro","Datu Salumay",
  "Gov. Paciano Bangoy","Gov. Vicente Duterte","Gumitan","Inayangan",
  "Kap. Tomas Monteverde, Sr.","Lapu-lapu","Leon Garcia, Sr.","Magsaysay",
  "Megkawayan","Rafael Castillo","Saloy","San Antonio","Santo Niño","Ubalde",
  "Waan","Wilfredo Aquino","Alfonso Angliongto Sr.","Vicente Hizon Sr.",
];

export const DAVAO_PUROKS = [
  "Purok 1","Purok 2","Purok 3","Purok 4","Purok 5",
  "Purok 6","Purok 7","Purok 8","Purok 9","Purok 10",
];
