export interface Hospital {
  id: number;
  name: string;
  category: string;
  sector: "Government" | "Private";
  address: string;
  district: string;
  nearestBarangays: string[];
}

export const DAVAO_HOSPITALS: Hospital[] = [
  {
    id: 1,
    name: "Southern Philippines Medical Center (SPMC)",
    category: "Level 3",
    sector: "Government",
    address: "J.P. Laurel Ave., Bajada, Davao City",
    district: "Poblacion",
    nearestBarangays: [
      "Barangay 19-B","Barangay 20-B","Barangay 18-B","Barangay 17-B",
      "Bucana","Matina Aplaya","Matina Crossing","Agdao","Sasa",
    ],
  },
  {
    id: 2,
    name: "Adventist Hospital-Davao",
    category: "Level 2",
    sector: "Private",
    address: "Km. 7 McArthur Highway, Bangkal, Talomo District",
    district: "Talomo",
    nearestBarangays: [
      "Talomo","Talomo River","Bago Aplaya","Dumoy","Matina Pangi",
      "Matina Crossing","Lizada","Catalunan Grande","Catalunan Pequeño",
    ],
  },
  {
    id: 3,
    name: "Alterado General Hospital",
    category: "Level 2",
    sector: "Private",
    address: "P. Villanueva St., Gov. V. Duterte, Agdao, Davao City",
    district: "Agdao",
    nearestBarangays: [
      "Agdao","Gov. Vicente Duterte","Rafael Castillo","Sasa","Panacan",
      "Tibungco","Bunawan","Cabantian","Buhangin",
    ],
  },
  {
    id: 4,
    name: "Anda Riverview Medical Center",
    category: "Level 2",
    sector: "Private",
    address: "Brgy. 2-A, Magallanes St., Davao City",
    district: "Poblacion",
    nearestBarangays: [
      "Barangay 2-A","Barangay 1-A","Barangay 3-A","Barangay 4-A",
      "Barangay 5-A","Barangay 6-A","Lapu-lapu","Riverside",
    ],
  },
  {
    id: 5,
    name: "Brokenshire Medical Center",
    category: "Level 3",
    sector: "Private",
    address: "Brokenshire Heights, Madapo, Poblacion District",
    district: "Poblacion",
    nearestBarangays: [
      "Barangay 8-A","Barangay 7-A","Barangay 9-A","Barangay 10-A",
      "Matina Crossing","Matina Aplaya","Bucana","Sasa",
    ],
  },
  {
    id: 6,
    name: "Buda Community Health Care Center",
    category: "Infirmary",
    sector: "Private",
    address: "Purok 1, Buda, Marilog District",
    district: "Marilog",
    nearestBarangays: [
      "Buda","Marilog","Tamugan","Datu Salumay","Tamayong",
      "Eden","Bantol","Baganihan",
    ],
  },
  {
    id: 7,
    name: "Camp Panacan Station Hospital",
    category: "Infirmary",
    sector: "Government",
    address: "Naval Station Felix Apolinario, Panacan, Davao City",
    district: "Panacan",
    nearestBarangays: [
      "Panacan","Tibungco","Bunawan","Ilang","Pampanga","Sasa",
      "Cabantian","Buhangin",
    ],
  },
  {
    id: 8,
    name: "Camp Quintin M. Merecido Hospital",
    category: "Infirmary",
    sector: "Government",
    address: "C.P. Garcia Highway, Camp Catitipan, Buhangin",
    district: "Buhangin",
    nearestBarangays: [
      "Buhangin","Cabantian","Communal","New Valencia","Mandug",
      "Panacan","Tibungco","Sasa",
    ],
  },
  {
    id: 9,
    name: "City Government of Davao - Marilog District Hospital",
    category: "Infirmary",
    sector: "Government",
    address: "Lower Kibalang, Brgy. Marilog, Marilog District",
    district: "Marilog",
    nearestBarangays: [
      "Marilog","Buda","Tamugan","Datu Salumay","Tamayong",
      "Malagos","Eden","Bantol",
    ],
  },
  {
    id: 10,
    name: "City Government of Davao - Paquibato District Hospital",
    category: "Infirmary",
    sector: "Government",
    address: "Paquibato Proper, Paquibato District",
    district: "Paquibato",
    nearestBarangays: [
      "Paquibato","Paradise Embak","Malabog","Mapula","Marapangi",
      "Manuel Guianga","Callawa","Dacudao",
    ],
  },
  {
    id: 11,
    name: "Clinica Isaguirre",
    category: "Infirmary",
    sector: "Private",
    address: "Villafuerte St., Calinan, Davao City",
    district: "Calinan",
    nearestBarangays: [
      "Calinan","Lacson","Cadalian","Catigan","Biao Guianga",
      "Biao Escuela","Biao Joaquin","Tugbok",
    ],
  },
  {
    id: 12,
    name: "Cure Philippines",
    category: "Level 1",
    sector: "Private",
    address: "Lanang, J.P. Laurel Avenue, Davao City",
    district: "Lanang",
    nearestBarangays: [
      "Sasa","Panacan","San Antonio","Cabantian","Lanang",
      "Tibungco","Ilang","Agdao",
    ],
  },
  {
    id: 13,
    name: "Davao Doctors Hospital",
    category: "Level 3",
    sector: "Private",
    address: "118 E. Quirino Ave., Davao City",
    district: "Poblacion",
    nearestBarangays: [
      "Barangay 11-B","Barangay 12-B","Barangay 13-B","Barangay 14-B",
      "Barangay 10-A","Barangay 9-A","Agdao","Matina Crossing",
    ],
  },
  {
    id: 14,
    name: "Davao Medical School Foundation",
    category: "Level 2",
    sector: "Private",
    address: "Dr. A. Gahol Ave., Bajada, Brgy. 19-B, Poblacion",
    district: "Poblacion",
    nearestBarangays: [
      "Barangay 19-B","Barangay 18-B","Barangay 20-B","Matina Aplaya",
      "Bucana","Matina Crossing","Talomo","Dumoy",
    ],
  },
  {
    id: 15,
    name: "Davao Mediquest Hospital",
    category: "Level 1",
    sector: "Private",
    address: "McArthur Highway, Brgy. Lizada, Toril",
    district: "Toril",
    nearestBarangays: [
      "Lizada","Toril","Daliao","Bago Aplaya","Sirawan",
      "Sibulan","Los Amigos","Catalunan Grande",
    ],
  },
  {
    id: 16,
    name: "Dr. Lorenzo B. Principe Clinic & Drugstore",
    category: "Infirmary",
    sector: "Private",
    address: "Purok 9, R. Magsaysay Street, Calinan",
    district: "Calinan",
    nearestBarangays: [
      "Calinan","Cadalian","Lacson","Biao Escuela","Catigan",
      "Tugbok","Manuel Guianga","Biao Joaquin",
    ],
  },
  {
    id: 17,
    name: "Ernesto Guadalupe Community Hospital",
    category: "Level 1",
    sector: "Private",
    address: "Jasmin St., San Nicolas, Daliao, Toril",
    district: "Toril",
    nearestBarangays: [
      "Daliao","Toril","Lizada","Sibulan","Sirawan",
      "Los Amigos","Baliok","Catalunan Pequeño",
    ],
  },
  {
    id: 18,
    name: "Gig Oca Robles Seamen's Hospital",
    category: "Level 2",
    sector: "Private",
    address: "R. Castillo Street, Centro Agdao, Davao City",
    district: "Agdao",
    nearestBarangays: [
      "Agdao","Gov. Vicente Duterte","Rafael Castillo","Leon Garcia, Sr.",
      "Barangay 21-C","Barangay 22-C","Barangay 23-C","Riverside",
    ],
  },
  {
    id: 19,
    name: "Holy Spirit Community Hospital of Davao",
    category: "Level 1",
    sector: "Private",
    address: "Sampaguita St., Mintal, Davao City",
    district: "Calinan",
    nearestBarangays: [
      "Mintal","Tugbok","Calinan","Indangan","Dumoy",
      "Catalunan Grande","Tacunan","Lamanan",
    ],
  },
  {
    id: 20,
    name: "Isaac T. Robillo Hospital Corporation",
    category: "Level 1",
    sector: "Private",
    address: "Km. 26, Davao-Bukidnon Road, Calinan District",
    district: "Calinan",
    nearestBarangays: [
      "Calinan","Cadalian","Lacson","Catigan","Biao Guianga",
      "Gumalang","Manambulan","Manuel Guianga",
    ],
  },
  {
    id: 21,
    name: "Lanang Premiere Doctors Hospital",
    category: "Level 2",
    sector: "Private",
    address: "DVO Park District, Dakudao Loop, Lanang, San Antonio",
    district: "Buhangin",
    nearestBarangays: [
      "San Antonio","Cabantian","Sasa","Panacan","Bunawan",
      "Ilang","Tibungco","Buhangin",
    ],
  },
  {
    id: 22,
    name: "Malta Medical Center",
    category: "Level 1",
    sector: "Private",
    address: "Km. 14 McArthur Highway, Toril",
    district: "Toril",
    nearestBarangays: [
      "Toril","Lizada","Daliao","Bago Aplaya","Catalunan Grande",
      "Catalunan Pequeño","Sibulan","Sirawan",
    ],
  },
  {
    id: 23,
    name: "Medical Mission Group Hospital",
    category: "Level 1",
    sector: "Private",
    address: "3rd Ave., Leon Garcia Street, Davao City",
    district: "Agdao",
    nearestBarangays: [
      "Leon Garcia, Sr.","Agdao","Rafael Castillo","Gov. Vicente Duterte",
      "Barangay 26-C","Barangay 27-C","Magsaysay","Ubalde",
    ],
  },
  {
    id: 24,
    name: "Metro Davao Medical and Research Center",
    category: "Level 2",
    sector: "Private",
    address: "Km. 4, J.P. Laurel Avenue, Brgy. 19-B, Poblacion",
    district: "Poblacion",
    nearestBarangays: [
      "Barangay 19-B","Barangay 18-B","Ma-a","Talomo","Matina Crossing",
      "Matina Aplaya","Dumoy","Bago Aplaya",
    ],
  },
  {
    id: 25,
    name: "Ricardo Limso Medical Center",
    category: "Level 2",
    sector: "Private",
    address: "V. Ilustre St., Davao City",
    district: "Poblacion",
    nearestBarangays: [
      "Barangay 15-B","Barangay 16-B","Barangay 14-B","Barangay 17-B",
      "Barangay 13-B","Agdao","Bucana","Matina Aplaya",
    ],
  },
  {
    id: 26,
    name: "San Pedro Hospital of Davao City",
    category: "Level 3",
    sector: "Private",
    address: "C. Guzman St., Davao City",
    district: "Poblacion",
    nearestBarangays: [
      "Barangay 6-A","Barangay 7-A","Barangay 5-A","Barangay 8-A",
      "Barangay 4-A","Matina Crossing","Ma-a","Waan",
    ],
  },
  {
    id: 27,
    name: "Specialists' Primary Care of Ilang",
    category: "Infirmary",
    sector: "Private",
    address: "Km. 17, Purok 19, Ilang, Bunawan",
    district: "Bunawan",
    nearestBarangays: [
      "Ilang","Bunawan","Panacan","Tibungco","Pampanga",
      "Sasa","Cabantian","San Antonio",
    ],
  },
  {
    id: 28,
    name: "St. Felix Medical Hospital",
    category: "Infirmary",
    sector: "Private",
    address: "Catotal Subdivision, Bago Aplaya, Talomo District",
    district: "Talomo",
    nearestBarangays: [
      "Bago Aplaya","Talomo","Lizada","Catalunan Grande","Dumoy",
      "Matina Pangi","Sibulan","Toril",
    ],
  },
  {
    id: 29,
    name: "Tibungco Doctors Hospital",
    category: "Infirmary",
    sector: "Private",
    address: "Along National Highway, Brgy. Tibungco",
    district: "Buhangin",
    nearestBarangays: [
      "Tibungco","Bunawan","Panacan","Ilang","Pampanga",
      "Cabantian","Buhangin","Sasa",
    ],
  },
  {
    id: 30,
    name: "United Davao Specialists Hospital",
    category: "Level 2",
    sector: "Private",
    address: "Km. 4 McArthur Highway, Maa, Talomo District",
    district: "Talomo",
    nearestBarangays: [
      "Ma-a","Matina Crossing","Matina Aplaya","Talomo","Waan",
      "Catalunan Grande","Dumoy","Barangay 19-B",
    ],
  },
  {
    id: 31,
    name: "Viacrucis Infirmary",
    category: "Infirmary",
    sector: "Private",
    address: "Central 1, Binugao, Toril",
    district: "Toril",
    nearestBarangays: [
      "Binugao","Toril","Daliao","Baliok","Sirawan",
      "Sibulan","Catalunan Pequeño","Bago Aplaya",
    ],
  },
];
